{
  "formatVersion": "1.1",
  "component": {
    "group": "moe.luminolmc",
    "module": "hyacinthusclip",
    "version": "3.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hyacinthusclip-3.0.18.jar",
          "url": "hyacinthusclip-3.0.18.jar",
          "size": 3063930,
          "sha512": "aec9ce08a535eaa4a016f3d9a85261e1728f56404b061233573e685e1c39865753ccf47736867dbdab92baf827df05006d85404cf6ee2dad61e412575a7884f9",
          "sha256": "4a77eff7c394ccea7fa1c263dae19409e0652a7bd9a1058ff8f03fc8a81f7c2f",
          "sha1": "0170e45ab6f4230850110da2b0524fb7e2865021",
          "md5": "1ad8d0767dbdffbbbf22a2b8cc4b1ffd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hyacinthusclip-3.0.18.jar",
          "url": "hyacinthusclip-3.0.18.jar",
          "size": 3063930,
          "sha512": "aec9ce08a535eaa4a016f3d9a85261e1728f56404b061233573e685e1c39865753ccf47736867dbdab92baf827df05006d85404cf6ee2dad61e412575a7884f9",
          "sha256": "4a77eff7c394ccea7fa1c263dae19409e0652a7bd9a1058ff8f03fc8a81f7c2f",
          "sha1": "0170e45ab6f4230850110da2b0524fb7e2865021",
          "md5": "1ad8d0767dbdffbbbf22a2b8cc4b1ffd"
        }
      ]
    }
  ]
}
