swm:
  enabled: true
  loader:
    type: file
    file:
      path: slime_worlds
    mysql:
      host: 127.0.0.1
      port: 3306
      database: slime_worlds
      username: ""
      password: ""
      use-ssl: false
    mongo:
      host: 127.0.0.1
      port: 27017
      database: slime_worlds
      collection: worlds
      username: ""
      password: ""
      auth-source: admin
    redis:
      uri: redis://127.0.0.1:6379
  load-worlds: []
  auto-save-interval-minutes: 5
